

-- ATENCAO!!! ESSE ARQUIVO IRÁ APAGAR TODOS OS DADOS JÁ EXISTENTES NO BANCO DE DADOS, E RECRIAR O BANCO DE DADOS DO ZERO. APENAS EXECUTE ESSE ARQUIVO EM CASO DE REINICIAR OS DADOS ARMAZENADOS, E INICIAR O BANCO DE DADOS APENAS COM OS "INSERTS" PRESENTES NO ARQUIVO "restaurante_inserts.sql"
-- DO CONTRARIO, PERMANECA SEM EXECUTAR ESTE ARQUIVO!!!


SET DATEFORMAT YMD
USE master
GO
IF EXISTS (SELECT * FROM SYS.databases WHERE NAME = 'RESTAURANTESEA')
ALTER DATABASE RESTAURANTESEA SET SINGLE_USER WITH ROLLBACK IMMEDIATE
IF EXISTS (SELECT * FROM SYS.databases WHERE NAME = 'RESTAURANTESEA')
DROP DATABASE RESTAURANTESEA
GO
CREATE DATABASE RESTAURANTESEA
GO
USE RESTAURANTESEA
GO